
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author felipeec
 */
public class TelaContagemUSA extends javax.swing.JFrame {

    /**
     * Creates new form TelaContagemUSA
     */
    public TelaContagemUSA() {
        initComponents();
        setSize(1024,768);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTexto = new javax.swing.JLabel();
        lbl01 = new javax.swing.JLabel();
        lbl02 = new javax.swing.JLabel();
        lbl03 = new javax.swing.JLabel();
        lbl04 = new javax.swing.JLabel();
        lbl05 = new javax.swing.JLabel();
        lbl06 = new javax.swing.JLabel();
        lbl07 = new javax.swing.JLabel();
        lbl08 = new javax.swing.JLabel();
        lbl09 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();
        lblSaber = new javax.swing.JLabel();
        lblTelaUSA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(50, 150, 0, 0));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        lblTexto.setFont(new java.awt.Font("Showcard Gothic", 0, 120)); // NOI18N
        lblTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblTexto);
        lblTexto.setBounds(50, 200, 420, 130);

        lbl01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl01MouseClicked(evt);
            }
        });
        getContentPane().add(lbl01);
        lbl01.setBounds(10, 50, 80, 90);

        lbl02.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl02MouseClicked(evt);
            }
        });
        getContentPane().add(lbl02);
        lbl02.setBounds(120, 70, 80, 100);

        lbl03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl03MouseClicked(evt);
            }
        });
        getContentPane().add(lbl03);
        lbl03.setBounds(230, 50, 80, 100);

        lbl04.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl04MouseClicked(evt);
            }
        });
        getContentPane().add(lbl04);
        lbl04.setBounds(330, 70, 80, 90);

        lbl05.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl05MouseClicked(evt);
            }
        });
        getContentPane().add(lbl05);
        lbl05.setBounds(440, 90, 80, 100);

        lbl06.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl06MouseClicked(evt);
            }
        });
        getContentPane().add(lbl06);
        lbl06.setBounds(550, 70, 80, 90);

        lbl07.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl07MouseClicked(evt);
            }
        });
        getContentPane().add(lbl07);
        lbl07.setBounds(650, 20, 90, 100);

        lbl08.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl08MouseClicked(evt);
            }
        });
        getContentPane().add(lbl08);
        lbl08.setBounds(760, 40, 80, 100);

        lbl09.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl09MouseClicked(evt);
            }
        });
        getContentPane().add(lbl09);
        lbl09.setBounds(870, 20, 80, 100);

        lbl10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl10MouseClicked(evt);
            }
        });
        getContentPane().add(lbl10);
        lbl10.setBounds(910, 140, 100, 100);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("voltar ao menu principal");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 710, 420, 40);

        lblSair.setFont(new java.awt.Font("Showcard Gothic", 0, 30)); // NOI18N
        lblSair.setForeground(new java.awt.Color(51, 255, 0));
        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Moldura.png"))); // NOI18N
        lblSair.setText("Voltar ao Menu principal");
        lblSair.setToolTipText("");
        lblSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
        });
        getContentPane().add(lblSair);
        lblSair.setBounds(380, 700, 450, 60);

        lblSaber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N
        getContentPane().add(lblSaber);
        lblSaber.setBounds(860, 600, 160, 170);

        lblTelaUSA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Funco Contagem USA.jpg"))); // NOI18N
        getContentPane().add(lblTelaUSA);
        lblTelaUSA.setBounds(0, 0, 1024, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    TocarSom som = new TocarSom();
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        TelaJogos tll = new TelaJogos();
        tll.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void lbl01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl01MouseClicked
        som.playSound("one.wav");
        lblTexto.setText("ONE");
    }//GEN-LAST:event_lbl01MouseClicked

    private void lbl02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl02MouseClicked
        som.playSound("two.wav");
        lblTexto.setText("TWO");
    }//GEN-LAST:event_lbl02MouseClicked

    private void lbl03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl03MouseClicked
        som.playSound("three.wav");
        lblTexto.setText("THREE");
    }//GEN-LAST:event_lbl03MouseClicked

    private void lbl04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl04MouseClicked
        som.playSound("four.wav");
        lblTexto.setText("FOUR");
    }//GEN-LAST:event_lbl04MouseClicked

    private void lbl05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl05MouseClicked
        som.playSound("five.wav");
        lblTexto.setText("FIVE");
    }//GEN-LAST:event_lbl05MouseClicked

    private void lbl06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl06MouseClicked
        som.playSound("six.wav");
        lblTexto.setText("SIX");
    }//GEN-LAST:event_lbl06MouseClicked

    private void lbl07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl07MouseClicked
        som.playSound("seven.wav");
        lblTexto.setText("SEVEN");
    }//GEN-LAST:event_lbl07MouseClicked

    private void lbl08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl08MouseClicked
        som.playSound("eight.wav");
        lblTexto.setText("EIGHT");
    }//GEN-LAST:event_lbl08MouseClicked

    private void lbl09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl09MouseClicked
        som.playSound("nine.wav");
        lblTexto.setText("NINE");
    }//GEN-LAST:event_lbl09MouseClicked

    private void lbl10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl10MouseClicked
        som.playSound("ten.wav");
        lblTexto.setText("TEN");
    }//GEN-LAST:event_lbl10MouseClicked

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        TelaEscolha JogoEscolha = new TelaEscolha();
        JogoEscolha.setLocationRelativeTo(null);
	JogoEscolha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaContagemUSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaContagemUSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaContagemUSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaContagemUSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaContagemUSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl01;
    private javax.swing.JLabel lbl02;
    private javax.swing.JLabel lbl03;
    private javax.swing.JLabel lbl04;
    private javax.swing.JLabel lbl05;
    private javax.swing.JLabel lbl06;
    private javax.swing.JLabel lbl07;
    private javax.swing.JLabel lbl08;
    private javax.swing.JLabel lbl09;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lblSaber;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblTelaUSA;
    private javax.swing.JLabel lblTexto;
    // End of variables declaration//GEN-END:variables
}
