

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author felipeec
 */
public class TelaContagemPT extends javax.swing.JFrame {

    /**
     * Creates new form TelaContagemPT
     */
    public TelaContagemPT() {
        initComponents();
        setSize(1024,768);
        numeros();
    }
    
//    public void tempo(Component c){
//    Timer t = new Timer(2500, new ActionListener() {
//        @Override
//        public void actionPerformed(ActionEvent ae) {
//        c.setVisible(false);
//        }
//        
//    });
//    t.start();
//            }
    public void numeros (){
        lbl01.setVisible(false);
        lbl02.setVisible(false);
        lbl03.setVisible(false);
        lbl04.setVisible(false);
        lbl05.setVisible(false);
        lbl06.setVisible(false);
        lbl07.setVisible(false);
        lbl08.setVisible(false);
        lbl09.setVisible(false);
        lbl10.setVisible(false);
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl01 = new javax.swing.JLabel();
        lbl03 = new javax.swing.JLabel();
        lbl04 = new javax.swing.JLabel();
        lbl05 = new javax.swing.JLabel();
        lbl06 = new javax.swing.JLabel();
        lbl07 = new javax.swing.JLabel();
        lbl08 = new javax.swing.JLabel();
        lbl09 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl02 = new javax.swing.JLabel();
        lblUm = new javax.swing.JLabel();
        lblDois = new javax.swing.JLabel();
        lblTrês = new javax.swing.JLabel();
        lblQuatro = new javax.swing.JLabel();
        lblCinco = new javax.swing.JLabel();
        lblSeis = new javax.swing.JLabel();
        lblSete = new javax.swing.JLabel();
        lblOito = new javax.swing.JLabel();
        lblNove = new javax.swing.JLabel();
        lblDez = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();
        lblSaber = new javax.swing.JLabel();
        lblFundo_ContagemPT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(50, 50, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        lbl01.setFont(new java.awt.Font("Freestyle Script", 0, 48)); // NOI18N
        lbl01.setForeground(new java.awt.Color(255, 102, 51));
        lbl01.setText("UM");
        getContentPane().add(lbl01);
        lbl01.setBounds(220, 200, 60, 50);

        lbl03.setFont(new java.awt.Font("Freestyle Script", 0, 48)); // NOI18N
        lbl03.setForeground(new java.awt.Color(255, 102, 51));
        lbl03.setText("TRÊS");
        getContentPane().add(lbl03);
        lbl03.setBounds(520, 200, 90, 50);

        lbl04.setFont(new java.awt.Font("Freestyle Script", 0, 48)); // NOI18N
        lbl04.setForeground(new java.awt.Color(255, 102, 51));
        lbl04.setText("QUATRO");
        getContentPane().add(lbl04);
        lbl04.setBounds(660, 200, 150, 50);

        lbl05.setFont(new java.awt.Font("Freestyle Script", 0, 48)); // NOI18N
        lbl05.setForeground(new java.awt.Color(255, 102, 51));
        lbl05.setText("CINCO");
        getContentPane().add(lbl05);
        lbl05.setBounds(830, 200, 110, 50);

        lbl06.setFont(new java.awt.Font("Freestyle Script", 0, 48)); // NOI18N
        lbl06.setForeground(new java.awt.Color(255, 102, 51));
        lbl06.setText("SEIS");
        getContentPane().add(lbl06);
        lbl06.setBounds(210, 400, 80, 50);

        lbl07.setFont(new java.awt.Font("Freestyle Script", 0, 48)); // NOI18N
        lbl07.setForeground(new java.awt.Color(255, 102, 51));
        lbl07.setText("SETE");
        getContentPane().add(lbl07);
        lbl07.setBounds(360, 400, 90, 50);

        lbl08.setFont(new java.awt.Font("Freestyle Script", 0, 48)); // NOI18N
        lbl08.setForeground(new java.awt.Color(255, 102, 51));
        lbl08.setText("OITO");
        getContentPane().add(lbl08);
        lbl08.setBounds(520, 400, 90, 50);

        lbl09.setFont(new java.awt.Font("Freestyle Script", 0, 48)); // NOI18N
        lbl09.setForeground(new java.awt.Color(255, 102, 51));
        lbl09.setText("NOVE");
        getContentPane().add(lbl09);
        lbl09.setBounds(680, 400, 90, 50);

        lbl10.setFont(new java.awt.Font("Freestyle Script", 0, 48)); // NOI18N
        lbl10.setForeground(new java.awt.Color(255, 102, 51));
        lbl10.setText("DEZ");
        getContentPane().add(lbl10);
        lbl10.setBounds(850, 400, 70, 50);

        lbl02.setFont(new java.awt.Font("Freestyle Script", 0, 48)); // NOI18N
        lbl02.setForeground(new java.awt.Color(255, 102, 51));
        lbl02.setText("DOIS");
        getContentPane().add(lbl02);
        lbl02.setBounds(370, 200, 80, 50);

        lblUm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUmMouseClicked(evt);
            }
        });
        getContentPane().add(lblUm);
        lblUm.setBounds(190, 270, 110, 110);

        lblDois.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDois.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoisMouseClicked(evt);
            }
        });
        getContentPane().add(lblDois);
        lblDois.setBounds(350, 270, 110, 110);

        lblTrês.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTrês.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTrêsMouseClicked(evt);
            }
        });
        getContentPane().add(lblTrês);
        lblTrês.setBounds(510, 270, 110, 110);

        lblQuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuatroMouseClicked(evt);
            }
        });
        getContentPane().add(lblQuatro);
        lblQuatro.setBounds(670, 270, 100, 110);

        lblCinco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCincoMouseClicked(evt);
            }
        });
        getContentPane().add(lblCinco);
        lblCinco.setBounds(820, 270, 110, 100);

        lblSeis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSeis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSeisMouseClicked(evt);
            }
        });
        getContentPane().add(lblSeis);
        lblSeis.setBounds(190, 470, 110, 100);

        lblSete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSeteMouseClicked(evt);
            }
        });
        getContentPane().add(lblSete);
        lblSete.setBounds(350, 470, 100, 100);

        lblOito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOitoMouseClicked(evt);
            }
        });
        getContentPane().add(lblOito);
        lblOito.setBounds(510, 470, 100, 100);

        lblNove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNoveMouseClicked(evt);
            }
        });
        getContentPane().add(lblNove);
        lblNove.setBounds(670, 470, 100, 100);

        lblDez.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDez.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDezMouseClicked(evt);
            }
        });
        getContentPane().add(lblDez);
        lblDez.setBounds(820, 470, 110, 100);

        lblSair.setFont(new java.awt.Font("Showcard Gothic", 0, 30)); // NOI18N
        lblSair.setForeground(new java.awt.Color(51, 255, 0));
        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Botao voltar.png"))); // NOI18N
        lblSair.setText("Voltar ao Menu principal");
        lblSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
        });
        getContentPane().add(lblSair);
        lblSair.setBounds(570, 690, 450, 70);

        lblSaber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N
        getContentPane().add(lblSaber);
        lblSaber.setBounds(10, 10, 160, 170);

        lblFundo_ContagemPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo Contagem Numérica.jpg"))); // NOI18N
        getContentPane().add(lblFundo_ContagemPT);
        lblFundo_ContagemPT.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    TocarSom som = new TocarSom();
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        TelaJogos tll = new TelaJogos();
        tll.setVisible(true);
    }//GEN-LAST:event_formWindowClosing
  
    private void lblUmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUmMouseClicked
        numeros();
        som.playSound("01.wav");
        lbl01.setVisible(true);
    }//GEN-LAST:event_lblUmMouseClicked

    private void lblDoisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoisMouseClicked
        numeros();
        som.playSound("02.wav");
        lbl02.setVisible(true);
    }//GEN-LAST:event_lblDoisMouseClicked

    private void lblTrêsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrêsMouseClicked
        numeros();
        som.playSound("03.wav");
        lbl03.setVisible(true);
    }//GEN-LAST:event_lblTrêsMouseClicked

    private void lblQuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuatroMouseClicked
        numeros();
        som.playSound("04.wav");
        lbl04.setVisible(true);
    }//GEN-LAST:event_lblQuatroMouseClicked

    private void lblCincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCincoMouseClicked
        numeros();
        som.playSound("05.wav");
        lbl05.setVisible(true);
    }//GEN-LAST:event_lblCincoMouseClicked

    private void lblSeisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSeisMouseClicked
        numeros();
        som.playSound("06.wav");
        lbl06.setVisible(true);
    }//GEN-LAST:event_lblSeisMouseClicked

    private void lblSeteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSeteMouseClicked
        numeros();
        som.playSound("07.wav");
        lbl07.setVisible(true);
    }//GEN-LAST:event_lblSeteMouseClicked

    private void lblOitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOitoMouseClicked
        numeros();
        som.playSound("08.wav");
        lbl08.setVisible(true);
    }//GEN-LAST:event_lblOitoMouseClicked

    private void lblNoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNoveMouseClicked
        numeros();
        som.playSound("09.wav");
        lbl09.setVisible(true);
    }//GEN-LAST:event_lblNoveMouseClicked

    private void lblDezMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDezMouseClicked
        numeros();
        som.playSound("10.wav");
        lbl10.setVisible(true);
    }//GEN-LAST:event_lblDezMouseClicked

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
                TelaEscolha JogoEscolha = new TelaEscolha();
        JogoEscolha.setLocationRelativeTo(null);
	JogoEscolha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaContagemPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaContagemPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaContagemPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaContagemPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaContagemPT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl01;
    private javax.swing.JLabel lbl02;
    private javax.swing.JLabel lbl03;
    private javax.swing.JLabel lbl04;
    private javax.swing.JLabel lbl05;
    private javax.swing.JLabel lbl06;
    private javax.swing.JLabel lbl07;
    private javax.swing.JLabel lbl08;
    private javax.swing.JLabel lbl09;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lblCinco;
    private javax.swing.JLabel lblDez;
    private javax.swing.JLabel lblDois;
    private javax.swing.JLabel lblFundo_ContagemPT;
    private javax.swing.JLabel lblNove;
    private javax.swing.JLabel lblOito;
    private javax.swing.JLabel lblQuatro;
    private javax.swing.JLabel lblSaber;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblSeis;
    private javax.swing.JLabel lblSete;
    private javax.swing.JLabel lblTrês;
    private javax.swing.JLabel lblUm;
    // End of variables declaration//GEN-END:variables
}
