
import java.awt.Component;
import java.awt.Point;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author felipeec
 */
public class TelaLigueOsPares_1 extends javax.swing.JFrame {

//    public javax.swing.JLabel lbl01;
//    private javax.swing.JLabel lbl2;
//    private javax.swing.JLabel lbl3;
//    private javax.swing.JLabel lbl4;
//    private javax.swing.JLabel lbl5;
//    private javax.swing.JLabel lbl6;
//    private javax.swing.JLabel lblAmarelo;
//    private javax.swing.JLabel lblAzul;
//    private javax.swing.JLabel lblFundoCores;
//    private javax.swing.JLabel lblVerifica;
//    private javax.swing.JLabel lblVermelho;
    ImageIcon iconAzul = new ImageIcon(getClass().getResource("Azul.png"));
    ImageIcon iconAmarelo = new ImageIcon(getClass().getResource("Amarelo.png"));
    ImageIcon iconVermelho = new ImageIcon(getClass().getResource("Vermelho.png"));
    ImageIcon iconFim = new ImageIcon(getClass().getResource("Interrogação.png"));
            
    /**
     * Creates new form TelaLigueOsPares
     */
    public TelaLigueOsPares_1() {
        initComponents();
        setSize(1024,768);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl01 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lblVerifica = new javax.swing.JLabel();
        lblAzul = new javax.swing.JLabel();
        lblVermelho = new javax.swing.JLabel();
        lblAmarelo = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();
        lblVerde = new javax.swing.JLabel();
        lblLaranja = new javax.swing.JLabel();
        lblRoxo = new javax.swing.JLabel();
        lblSaber = new javax.swing.JLabel();
        lblFundoCores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setBounds(new java.awt.Rectangle(50, 150, 0, 0));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        lbl01.setForeground(new java.awt.Color(255, 102, 102));
        lbl01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Interrogação.png"))); // NOI18N
        lbl01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl01.setName("100"); // NOI18N
        lbl01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl01MouseClicked(evt);
            }
        });
        getContentPane().add(lbl01);
        lbl01.setBounds(220, 150, 130, 120);
        lbl01.getAccessibleContext().setAccessibleName("100");
        lbl01.getAccessibleContext().setAccessibleDescription("100");

        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Interrogação.png"))); // NOI18N
        lbl2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl2.setName("200"); // NOI18N
        lbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl2MouseClicked(evt);
            }
        });
        getContentPane().add(lbl2);
        lbl2.setBounds(220, 300, 140, 120);

        lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Interrogação.png"))); // NOI18N
        lbl3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl3.setName("300"); // NOI18N
        lbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl3MouseClicked(evt);
            }
        });
        getContentPane().add(lbl3);
        lbl3.setBounds(210, 460, 150, 120);

        lbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Interrogação.png"))); // NOI18N
        lbl4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl4.setName("400"); // NOI18N
        lbl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl4MouseClicked(evt);
            }
        });
        getContentPane().add(lbl4);
        lbl4.setBounds(430, 300, 130, 120);

        lbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Interrogação.png"))); // NOI18N
        lbl5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl5.setName("500"); // NOI18N
        lbl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl5MouseClicked(evt);
            }
        });
        getContentPane().add(lbl5);
        lbl5.setBounds(430, 460, 140, 120);

        lbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Interrogação.png"))); // NOI18N
        lbl6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl6.setName("600"); // NOI18N
        lbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl6MouseClicked(evt);
            }
        });
        getContentPane().add(lbl6);
        lbl6.setBounds(430, 150, 140, 120);

        lblVerifica.setFont(new java.awt.Font("Showcard Gothic", 0, 27)); // NOI18N
        lblVerifica.setForeground(new java.awt.Color(0, 255, 0));
        lblVerifica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Botao verificar-iloveimg-resized.png"))); // NOI18N
        lblVerifica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerifica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerificaMouseClicked(evt);
            }
        });
        getContentPane().add(lblVerifica);
        lblVerifica.setBounds(570, 610, 450, 80);

        lblAzul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAzul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAzulMouseClicked(evt);
            }
        });
        getContentPane().add(lblAzul);
        lblAzul.setBounds(30, 580, 80, 70);

        lblVermelho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVermelho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVermelhoMouseClicked(evt);
            }
        });
        getContentPane().add(lblVermelho);
        lblVermelho.setBounds(150, 650, 70, 60);

        lblAmarelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAmarelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAmareloMouseClicked(evt);
            }
        });
        getContentPane().add(lblAmarelo);
        lblAmarelo.setBounds(30, 690, 80, 70);

        lblSair.setFont(new java.awt.Font("Showcard Gothic", 0, 30)); // NOI18N
        lblSair.setForeground(new java.awt.Color(51, 255, 0));
        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Botao voltar.png"))); // NOI18N
        lblSair.setText("Voltar ao Menu principal");
        lblSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
        });
        getContentPane().add(lblSair);
        lblSair.setBounds(570, 695, 450, 60);

        lblVerde.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerdeMouseClicked(evt);
            }
        });
        getContentPane().add(lblVerde);
        lblVerde.setBounds(650, 180, 100, 90);

        lblLaranja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLaranja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLaranjaMouseClicked(evt);
            }
        });
        getContentPane().add(lblLaranja);
        lblLaranja.setBounds(650, 340, 100, 90);

        lblRoxo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRoxo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRoxoMouseClicked(evt);
            }
        });
        getContentPane().add(lblRoxo);
        lblRoxo.setBounds(640, 490, 110, 90);

        lblSaber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N
        getContentPane().add(lblSaber);
        lblSaber.setBounds(10, 10, 160, 170);

        lblFundoCores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Juntando Cores.jpg"))); // NOI18N
        getContentPane().add(lblFundoCores);
        lblFundoCores.setBounds(0, 0, 1020, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        TelaJogos tl = new TelaJogos();
        tl.setVisible(true);
    }//GEN-LAST:event_formWindowClosing
    
    int verificar;
    TocarSom som = new TocarSom();
    
    private void lbl01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl01MouseClicked
        if ( verificar == 100){
            lbl01.setIcon(iconAzul);
            lbl01.setName("100");
        }if ( verificar == 500){
            lbl01.setIcon(iconVermelho);
            lbl01.setName("500");
        }if ( verificar == 1000){
            lbl01.setIcon(iconAmarelo);
            lbl01.setName("1000");
        }
    }//GEN-LAST:event_lbl01MouseClicked

    private void lbl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl6MouseClicked
        if ( verificar == 100){
            lbl6.setIcon(iconAzul);
            lbl6.setName("100");
        }if ( verificar == 500){
            lbl6.setIcon(iconVermelho);
            lbl6.setName("500");
        }if ( verificar == 1000){
            lbl6.setIcon(iconAmarelo);
            lbl6.setName("1000");
        }
    }//GEN-LAST:event_lbl6MouseClicked

    private void lbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2MouseClicked
        if ( verificar == 100){
            lbl2.setIcon(iconAzul);
            lbl2.setName("100");
        }if ( verificar == 500){
            lbl2.setIcon(iconVermelho);
            lbl2.setName("500");
        }if ( verificar == 1000){
            lbl2.setIcon(iconAmarelo);
            lbl2.setName("1000");
        }
    }//GEN-LAST:event_lbl2MouseClicked

    private void lbl4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl4MouseClicked
        if ( verificar == 100){
            lbl4.setIcon(iconAzul);
            lbl4.setName("100");
        }if ( verificar == 500){
            lbl4.setIcon(iconVermelho);
            lbl4.setName("500");
        }if ( verificar == 1000){
            lbl4.setIcon(iconAmarelo);
            lbl4.setName("1000");
        }
    }//GEN-LAST:event_lbl4MouseClicked

    private void lbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl3MouseClicked
        if ( verificar == 100){
            lbl3.setIcon(iconAzul);
            lbl3.setName("100");
        }if ( verificar == 500){
            lbl3.setIcon(iconVermelho);
            lbl3.setName("500");
        }if ( verificar == 1000){
            lbl3.setIcon(iconAmarelo);
            lbl3.setName("1000");
        }
    }//GEN-LAST:event_lbl3MouseClicked

    private void lbl5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl5MouseClicked
        if ( verificar == 100){
            lbl5.setIcon(iconAzul);
            lbl5.setName("100");
        }if ( verificar == 500){
            lbl5.setIcon(iconVermelho);
            lbl5.setName("500");
        }if ( verificar == 1000){
            lbl5.setIcon(iconAmarelo);
            lbl5.setName("1000");
        }
    }//GEN-LAST:event_lbl5MouseClicked

    private void lblVerificaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerificaMouseClicked
        int verde = Integer.parseInt(lbl01.getName())+Integer.parseInt(lbl6.getName());
        int laranja = Integer.parseInt(lbl2.getName())+Integer.parseInt(lbl4.getName());
        int roxo = Integer.parseInt(lbl5.getName())+Integer.parseInt(lbl3.getName());
        
        if (verde == 1100 && laranja == 1500 && roxo == 600){
            JOptionPane.showMessageDialog(null, "Parabéns você acertou!");
        }else{
            JOptionPane.showMessageDialog(null, "A resposta está incorreta, tente novamente!");
        }
            lbl01.setIcon(iconFim);
            lbl2.setIcon(iconFim);
            lbl3.setIcon(iconFim);
            lbl4.setIcon(iconFim);
            lbl5.setIcon(iconFim);
            lbl6.setIcon(iconFim);
            lbl01.setName("8000");
            lbl2.setName("5000");
            lbl3.setName("10000");
    }//GEN-LAST:event_lblVerificaMouseClicked

    private void lblAzulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAzulMouseClicked
        verificar = 100;
        som.playSound("Azul.wav");
    }//GEN-LAST:event_lblAzulMouseClicked

    private void lblVermelhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVermelhoMouseClicked
        verificar = 500;
        som.playSound("Vermelho.wav");
    }//GEN-LAST:event_lblVermelhoMouseClicked

    private void lblAmareloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAmareloMouseClicked
        verificar = 1000;
        som.playSound("Amarelo.wav");
    }//GEN-LAST:event_lblAmareloMouseClicked

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        TelaEscolha JogoEscolha = new TelaEscolha();
        JogoEscolha.setLocationRelativeTo(null);
	JogoEscolha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblSairMouseClicked

    private void lblVerdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerdeMouseClicked
        som.playSound("Verde.wav");
    }//GEN-LAST:event_lblVerdeMouseClicked

    private void lblLaranjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLaranjaMouseClicked
        som.playSound("Laranja.wav");
    }//GEN-LAST:event_lblLaranjaMouseClicked

    private void lblRoxoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRoxoMouseClicked
        som.playSound("Roxo.wav");
    }//GEN-LAST:event_lblRoxoMouseClicked
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLigueOsPares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLigueOsPares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLigueOsPares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLigueOsPares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLigueOsPares().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lbl01;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lblAmarelo;
    private javax.swing.JLabel lblAzul;
    private javax.swing.JLabel lblFundoCores;
    private javax.swing.JLabel lblLaranja;
    private javax.swing.JLabel lblRoxo;
    private javax.swing.JLabel lblSaber;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblVerde;
    private javax.swing.JLabel lblVerifica;
    private javax.swing.JLabel lblVermelho;
    // End of variables declaration//GEN-END:variables
}
